apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-tool
  labels:
    app.kubernetes.io/name: mariadb-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb-tool
    spec:
      containers:
        - name: mariadb-tool
          image: localhost:5000/docker.io/bitnami/mariadb:10.5.12-debian-10-r0
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mariadb-root-password
                  name: my-mariadb
            - name: TZ
              value: Asia/Shanghai
