apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-tool
  labels:
    app.kubernetes.io/name: minio-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-tool
    spec:
      containers:
        - name: minio-tool
          image: docker.io/bitnami/minio-client:2022.8.11-debian-11-r3
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MINIO_SERVER_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: root-user
                  name: my-minio
            - name: MINIO_SERVER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: my-minio
            - name: MINIO_SERVER_HOST
              value: my-minio
            - name: MINIO_SERVER_PORT
              value: "9000"
          command:
            - tail
            - -f
            - /etc/hosts
