apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-tool
  labels:
    app.kubernetes.io/name: redis-cluster-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster-tool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cluster-tool
    spec:
      containers:
        - name: redis-cluster-tool
          image: localhost:5000/docker.io/bitnami/redis-cluster:6.2.2-debian-10-r0
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: my-redis-cluster
            - name: TZ
              value: Asia/Shanghai
          command:
            - tail
            - -f
            - /etc/hosts
